"""empty message

Revision ID: 337b63eb40d9
Revises: d7aa3598ff69
Create Date: 2020-07-01 23:51:17.455371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337b63eb40d9'
down_revision = 'd7aa3598ff69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
