"""empty message

Revision ID: 526b8aaa4b94
Revises: 337b63eb40d9
Create Date: 2020-07-02 00:05:46.490139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526b8aaa4b94'
down_revision = '337b63eb40d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
